### ISSUE TITLE
Botão "Ver Reclamações" na página "Empresas" não está navegável

### ISSUE THREAD

**Issue by ronnyjohnti** [reclama-dev/reclama-dev#2]
### Descrição do bug
Botão "Ver Reclamações" do card da Empresa não está navegável.

### Como reproduzir
1. Acessando a página "Empresas"
2. Clicando em "Ver Reclamações" em um card de empresa

### Screenshots
![image](https://github.com/reclama-dev/reclama-dev/assets/42920699/2614f2b8-e3b4-4770-8339-17aed2874a81)

**Comment by nihey** [comment]
@ronnyjohnti Obrigado pelo report do erro, acabei de enviar uma atualização que deverá resolver ela aqui: https://github.com/reclama-dev/reclama-dev/pull/3
